// vendor/subbit/aiken/lib/mark/vectors.ak: what this package's own TypeScript produces for the
// Subbit validator (IOU bodies and signatures, tags, datums, redeemers), for the Aiken tests next
// to the validator to check against. Write it with: npx tsx test/subbit-aiken-vectors.ts
// (subbit-aiken-vectors.test.ts fails while the file is out of date.)
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { Data, TransactionHash, TransactionInput } from "@evolution-sdk/evolution";
import { Redeemer, SUBBIT_HASH, Step, datumData, iouBody, iouSignerFromSeed, tagFromInput, type Constants, type Stage } from "../src/subbit.ts";

const keyA = iouSignerFromSeed(new Uint8Array(32).fill(1));
const keyB = iouSignerFromSeed(new Uint8Array(32).fill(2));
const input = (index: bigint) => new TransactionInput.TransactionInput({ transactionId: TransactionHash.fromHex("ab".repeat(32)), index });
const tag1 = tagFromInput(input(0n));
const tag2 = tagFromInput(input(1n));
const consumer = "11".repeat(28);
const provider = "22".repeat(28);
const policy = "33".repeat(28);
const tokenName = Buffer.from("USDM").toString("hex");
const closePeriod = 3_600_000n;

// Every CBOR integer width, each side of each boundary, and amounts the tests use.
const owed = [0n, 1n, 23n, 24n, 255n, 256n, 65_535n, 65_536n, 1_000_000n, 2_500_000n, 5_000_000n, 10_000_000n, 4_294_967_295n, 4_294_967_296n, 1_000_000_000_000n, 2n ** 64n - 1n];

const constants = (currency: Constants["currency"]): Constants => ({ tag: tag1, currency, iouKey: keyA.publicKey, consumer, provider, closePeriodMs: closePeriod });
const ada = constants({ kind: "ada" });
const token = constants({ kind: "asset", policy, name: tokenName });
const datum = (c: Constants, s: Stage) => Data.toCBORHex(datumData(c, s));
const sig = "44".repeat(64);

const bytes = (h: string) => `#"${h}"`;
const pairs = (xs: Array<[bigint, string]>) => `[\n${xs.map(([n, h]) => `  (${n}, ${bytes(h)}),`).join("\n")}\n]`;

export const VECTORS_PATH = fileURLToPath(new URL("../vendor/subbit/aiken/lib/mark/vectors.ak", import.meta.url));

/** The vectors module, as the client's code produces it now. */
export const vectorsModule = () => `//// Test vectors from subbit-x402's own TypeScript (src/subbit.ts): what the client signs and
//// writes for this validator. Generated by test/subbit-aiken-vectors.ts; rerun it, don't edit.

/// The validator's hash, as src/subbit.ts reads it from vendor/subbit/plutus.json.
pub const subbit_hash: ByteArray =
  ${bytes(SUBBIT_HASH)}

/// IOU key A: the Ed25519 key of the seed 0x01 x 32.
pub const iou_key_a: ByteArray =
  ${bytes(keyA.publicKey)}

/// IOU key B: the seed 0x02 x 32.
pub const iou_key_b: ByteArray =
  ${bytes(keyB.publicKey)}

/// Tags as the client makes them (ADR tag.md's default): blake2b-256 of the input ab..ab#0, and #1.
pub const tag_1: ByteArray =
  ${bytes(tag1)}

pub const tag_2: ByteArray =
  ${bytes(tag2)}

pub const consumer: ByteArray =
  ${bytes(consumer)}

pub const provider: ByteArray =
  ${bytes(provider)}

pub const policy: ByteArray =
  ${bytes(policy)}

pub const token_name: ByteArray = ${bytes(tokenName)}

pub const close_period: Int = ${closePeriod}

/// (owed, key A's signature of the IOU (tag_1, owed)), across every CBOR integer width.
pub const ious_a_tag_1: List<(Int, ByteArray)> =
  ${pairs(owed.map((n) => [n, keyA.sign(tag1, n)]))}

/// (owed, the IOU body the client signs for (tag_1, owed)).
pub const bodies_tag_1: List<(Int, ByteArray)> =
  ${pairs(owed.map((n) => [n, Buffer.from(iouBody(tag1, n)).toString("hex")]))}

/// Key A's IOU for (tag_2, 5_000_000): valid, but for another channel.
pub const iou_a_tag_2_5m: ByteArray =
  ${bytes(keyA.sign(tag2, 5_000_000n))}

/// Key B's signature of (tag_1, 5_000_000): the right body, the wrong key.
pub const iou_b_tag_1_5m: ByteArray =
  ${bytes(keyB.sign(tag1, 5_000_000n))}

/// For batches: (tag of the input ab..ab#i, key A's IOU for (that tag, 5_000_000)), i = 0..3.
pub const batch_ious: List<(ByteArray, ByteArray)> =
  [\n${[0n, 1n, 2n, 3n].map((i) => `  (${bytes(tagFromInput(input(i)))}, ${bytes(keyA.sign(tagFromInput(input(i)), 5_000_000n))}),`).join("\n")}\n]

/// Datums as the client writes them (datumData), in CBOR. Constants: tag_1, key A, consumer,
/// provider, close_period; the currency is ADA, or policy.token_name.
pub const datum_opened_ada: ByteArray =
  ${bytes(datum(ada, { kind: "opened", subbed: 2_500_000n }))}

pub const datum_closed_token: ByteArray =
  ${bytes(datum(token, { kind: "closed", subbed: 7n, elapseAt: 1_790_000_000_000n }))}

pub const datum_settled_ada: ByteArray =
  ${bytes(datum(ada, { kind: "settled" }))}

/// The signature in the redeemer vectors' steps.
pub const step_sig: ByteArray =
  ${bytes(sig)}

/// Redeemers as the client writes them, with step_sig in their steps.
pub const redeemer_main: ByteArray =
  ${bytes(Data.toCBORHex(Redeemer.main([Step.add(), Step.sub(5_000_000n, sig), Step.close(), Step.settle(7n, sig), Step.end(), Step.elapse()])))}

pub const redeemer_defer: ByteArray = ${bytes(Data.toCBORHex(Redeemer.defer()))}

pub const redeemer_mutual: ByteArray = ${bytes(Data.toCBORHex(Redeemer.mutual()))}
`;

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(VECTORS_PATH, vectorsModule());
  console.log(`wrote ${VECTORS_PATH}: ${owed.length} IOUs, ${owed.length} bodies, 3 datums, 3 redeemers`);
}
